import type { Metadata } from 'next';
import LegalLayout from '../components/LegalLayout';
import { company } from '../lib/company';
import { ROUTES } from '../lib/routes';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Margadeshaka terms of service for using our website and products.',
  alternates: { canonical: ROUTES.terms },
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" path={ROUTES.terms} lastUpdated="May 7, 2026">
      <p>
        These terms govern your use of <a href="https://margadeshaka.com">margadeshaka.com</a> and our
        products (Sakha and Dronacharya). By using any of these services, you agree to these terms.
      </p>

      <h2 data-reveal="up">1. Who We Are</h2>
      <p>
        Margadeshaka (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;) is a startup based in India building
        AI products that combine Indian wisdom traditions with modern multi-agent AI systems.
      </p>

      <h2 data-reveal="up">2. Eligibility</h2>
      <p>
        You must be at least 13 years old (or the age of digital consent in your jurisdiction) to use our
        services. By signing up, you confirm that you meet this requirement and that the information you
        provide is accurate.
      </p>

      <h2 data-reveal="up">3. Your Account</h2>
      <ul>
        <li>You are responsible for maintaining the security of your account credentials.</li>
        <li>You are responsible for all activity under your account.</li>
        <li>Notify us immediately at <a href="mailto:contact@margadeshaka.com">contact@margadeshaka.com</a> of any unauthorized use.</li>
      </ul>

      <h2 data-reveal="up">4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the service for unlawful purposes or in violation of these terms.</li>
        <li>Attempt to reverse-engineer, scrape, or disrupt our systems.</li>
        <li>Submit content that is harmful, abusive, harassing, or infringes on others&apos; rights.</li>
        <li>Use the AI companions to generate harmful, illegal, or misleading content.</li>
        <li>Resell or redistribute our service without written permission.</li>
      </ul>

      <h2 data-reveal="up">5. AI-Generated Content</h2>
      <p>
        Our AI companions provide guidance based on input you provide. AI responses are generated by language
        models and may contain errors, inaccuracies, or content that does not reflect our views. <strong>AI
        output is not professional advice.</strong> Specifically:
      </p>
      <ul>
        <li>Sakha is not a substitute for licensed mental-health, medical, financial, or legal professionals.</li>
        <li>Sakha&apos;s guidance is for self-reflection and emotional support, not a substitute for professional medical, mental-health, legal, or financial advice, and not for making consequential decisions in isolation.</li>
        <li>If you are in crisis, please contact your local emergency services or a mental-health helpline.</li>
      </ul>

      <h2 data-reveal="up">6. Intellectual Property</h2>
      <p>
        We own the Margadeshaka name, logos, and the software running our services. You retain ownership of
        the content you submit (e.g., your conversations), and grant us a limited license to process it solely
        to provide the service.
      </p>

      <h2 data-reveal="up">7. Beta and Pre-release Products</h2>
      <p>
        Some of our products (currently Sakha) are in beta. Beta features may be unstable, change without
        notice, or be discontinued. Use them with reasonable expectations.
      </p>

      <h2 data-reveal="up">8. Pricing and Payment</h2>
      <p>
        Free tiers are available where indicated. Paid plans, when offered, will be billed per the pricing
        page in-product. You can cancel paid plans at any time; refunds are at our discretion.
      </p>

      <h2 data-reveal="up">9. Termination</h2>
      <p>
        You can stop using the service at any time and delete your account. We may suspend or terminate
        accounts that violate these terms or pose a risk to users. We will give reasonable notice unless
        immediate action is required.
      </p>

      <h2 data-reveal="up">10. Disclaimers</h2>
      <p>
        The service is provided &quot;as is&quot; without warranties of any kind. We do not warrant that the
        service will be uninterrupted, error-free, or secure, or that AI responses will be accurate.
      </p>

      <h2 data-reveal="up">11. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, Margadeshaka is not liable for indirect, incidental, special,
        consequential, or punitive damages, or any loss of profits or data arising from your use of the service.
      </p>

      <h2 data-reveal="up">12. Governing Law</h2>
      <p>
        {/* Forum reads from the registered office in company.ts rather than being
            hardcoded: this clause previously named Mumbai while /compliance
            published the registered office as Mohali, Punjab. Deriving it from
            one source means the two pages cannot disagree again. */}
        These terms are governed by the laws of India. Disputes shall be resolved in the courts of{' '}
        {company.registeredOffice.city}, {company.registeredOffice.state},{' '}
        {company.registeredOffice.country}, where {company.legalNameTitleCase} has its registered
        office, unless local consumer-protection laws require otherwise.
      </p>

      <h2 data-reveal="up">13. Changes to These Terms</h2>
      <p>
        We may update these terms. Material changes will be announced in-product or via email. Continued use
        after a change constitutes acceptance of the new terms.
      </p>

      <h2 data-reveal="up">14. Contact</h2>
      <p>
        Questions: <a href="mailto:contact@margadeshaka.com">contact@margadeshaka.com</a>
      </p>
    </LegalLayout>
  );
}
