name: Playwright Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, webkit]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps ${{ matrix.project }}
    
    - name: Build application
      run: npm run build
      
    - name: Run Playwright tests
      run: npx playwright test --project=${{ matrix.project }} --reporter=github
      env:
        CI: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.project }}
        path: |
          playwright-report/
          test-results/
        retention-days: 30

  accessibility-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    
    - name: Build application
      run: npm run build
      
    - name: Run Accessibility Tests
      run: npm run test:accessibility
      env:
        CI: true
    
    - name: Upload accessibility results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: accessibility-report
        path: |
          playwright-report/
          test-results/
        retention-days: 30

  performance-tests:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    
    - name: Build application
      run: npm run build
      
    - name: Run Performance Tests
      run: npm run test:performance
      env:
        CI: true
    
    - name: Upload performance results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-report
        path: |
          playwright-report/
          test-results/
        retention-days: 30

  visual-regression:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    
    - name: Build application
      run: npm run build
      
    - name: Run Visual Regression Tests
      run: npm run test:visual
      env:
        CI: true
    
    - name: Upload visual test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: visual-regression-report
        path: |
          playwright-report/
          test-results/
        retention-days: 30

  # Merge all test results
  combine-results:
    if: always()
    needs: [test, accessibility-tests, performance-tests, visual-regression]
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create combined report
      run: |
        echo "## Test Results Summary" > test-summary.md
        echo "" >> test-summary.md
        echo "### Cross-browser Tests" >> test-summary.md
        echo "- Status: ${{ needs.test.result }}" >> test-summary.md
        echo "" >> test-summary.md
        echo "### Accessibility Tests" >> test-summary.md
        echo "- Status: ${{ needs.accessibility-tests.result }}" >> test-summary.md
        echo "" >> test-summary.md
        echo "### Performance Tests" >> test-summary.md
        echo "- Status: ${{ needs.performance-tests.result }}" >> test-summary.md
        echo "" >> test-summary.md
        echo "### Visual Regression Tests" >> test-summary.md
        echo "- Status: ${{ needs.visual-regression.result }}" >> test-summary.md
        
    - name: Upload combined results
      uses: actions/upload-artifact@v4
      with:
        name: combined-test-results
        path: |
          test-summary.md
          */
        retention-days: 30